# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'lazymetro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lazymetro
	pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
	pod 'RealmSwift'
    pod 'IDPRootViewGettable', :git => 'https://github.com/idapgroup/IDPRootViewGettable.git'
	pod 'GoogleMaps'
pod 'RAMAnimatedTabBarController'
pod 'Result', '~> 3.0.0'

end
